import {
  Bot,
  Box,
  Brain,
  Car,
  Cloud,
  Crosshair,
  Eye,
  Factory,
  FileText,
  Gamepad2,
  Glasses,
  Globe,
  HardHat,
  HeartPulse,
  Layers,
  MapIcon,
  Monitor,
  Network,
  Paintbrush,
  Plane,
  Radio,
  ScanSearch,
  Search,
  Shield,
  ShieldCheck,
  ShieldEllipsis,
  Sofa,
  Train,
  Users,
  Waves,
  Wrench,
} from "lucide-react";
import type { ReactNode } from "react";

export interface Service {
  icon: ReactNode;
  title: string;
  desc: string;
  tag: string;
  image: string;
}

export interface Product {
  icon: ReactNode;
  name: string;
  desc: string;
  image: string;
}

export interface Industry {
  icon: ReactNode;
  name: string;
  desc: string;
  image: string;
  bannerImage?: string;
}

export type AppAreaGroup = { category: string; items: string[] };
export type ApplicationAreaEntry = string | AppAreaGroup;

export function slugify(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Custom VR Headset icon (person wearing Meta Quest style)
function VRHeadsetIcon({ className }: { className?: string }) {
  return (
    <svg
      role="img"
      aria-label="VR Headset"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
    >
      {/* Head */}
      <circle cx="12" cy="7" r="3" />
      {/* VR Headset on face */}
      <rect x="5" y="11" width="14" height="7" rx="3" />
      {/* Lens left */}
      <circle cx="9" cy="14.5" r="1.5" />
      {/* Lens right */}
      <circle cx="15" cy="14.5" r="1.5" />
      {/* Strap */}
      <path d="M5 14 Q2 14 2 11" />
      <path d="M19 14 Q22 14 22 11" />
    </svg>
  );
}

export const SERVICES: Service[] = [
  {
    icon: <VRHeadsetIcon className="w-7 h-7" />,
    title: "Virtual Reality (VR)",
    desc: "Immersive VR solutions for operational and maintenance training, interactive simulations, product and concept visualization, design studies, and marketing applications optimized for performance across a wide range of platforms and devices",
    tag: "Immersive Training · 3D Simulation · Product Experience · Design Studies · Sales & Marketing · Multi-user Collaboration · Scenario-based Training · Performance Analytics · IoT Integration · Digital Twins · AI Adaptive Learning · Voice & Gesture Control · Multi-language Support · Role-based Access · Aircraft Training · ATC Simulation · Automotive Training · Mining & Construction · Transport Systems · Healthcare Training · Defence Training · Weapon Simulators · Driving Simulators · Fire Safety Training · Emergency Response · Industrial Safety · Gaming & Entertainment · Windows · WebGL · iOS · Android · Meta Quest · HTC Vive · Pico · Apple Vision Pro · Aerospace · Defense · Homeland Security · Automotive · Engineering · Mining · Transport · Healthcare · Manufacturing · Gaming",
    image: "/assets/generated/service-vr.dim_800x500.jpg",
  },
  {
    icon: <Eye className="w-7 h-7" />,
    title: "Augmented Reality (AR)",
    desc: "Augmented Reality (AR) solutions for maintenance training, education, technical assistance, product trials, interactive walkthroughs, and sales and marketing applications.",
    tag: "Marker-based AR · Markerless AR · Object Tracking · Mobile AR · Remote Assistance · AR Instruction Manuals · Product Visualization · IoT Integration · Real-time Data Overlays · Cloud AR · Multi-user AR · Multi-language Support · Offline Functionality · MRO Guidance · Assembly Assistance · Field Service · Quality Inspection · Retail & E-commerce · Pharmaceutical Training · Construction Visualization · Logistics & Warehouse · Automotive Maintenance · Tourism & Education · Marketing Campaigns · Smart City Visualization · Android · iOS · RealWear · Vuzix · AR Glasses · Aerospace · Defense · Homeland Security · Automotive · Engineering · Mining · Transport · Healthcare · Manufacturing · Gaming",
    image: "/assets/generated/service-ar.dim_800x500.jpg",
  },
  {
    icon: <Layers className="w-7 h-7" />,
    title: "Mixed Reality (MR)",
    desc: "Blended MR experiences that merge physical and digital worlds for advanced training, collaboration, and design review.",
    tag: "Holographic Visualization · Spatial Mapping · Collaborative Design Reviews · Hands-free Workflows · Gesture & Voice Control · Real-time Data Overlays · Digital Twin Integration · IoT Integration · Guided Maintenance Workflows · Remote Expert Assistance · Object Tracking · Multi-user MR · Cloud Connectivity · Industrial MRO · Assembly Workflows · Design Reviews · Manufacturing Optimization · Quality Inspection · Field Service · Healthcare Training · Construction Visualization · Energy & Oil Gas · Warehouse & Logistics · Smart Factory · Industry 4.0 · HoloLens · Magic Leap · Aerospace · Defense · Homeland Security · Automotive · Engineering · Mining · Transport · Healthcare · Manufacturing · Gaming",
    image: "/assets/generated/service-mr.dim_800x500.jpg",
  },
  {
    icon: <Monitor className="w-7 h-7" />,
    title: "Visual Simulation (VS)",
    desc: "Visual Simulation services encompassing optimized 3D model and terrain development, scenario creation, high performance visual simulation application development, and desktop as well as hardware-in-the-loop simulator development.",
    tag: "3D Terrain Development · Geo-specific Terrains · Simulation Application Development · Desktop Simulators · Hardware-in-the-loop · HIL Simulators · Real-time Rendering · Scenario-based Simulation · Physics-based Modeling · Multi-user Simulation · AI-driven Simulation · Digital Twin Integration · Large-scale Environments · High-performance Optimization · Aerospace Simulation · Defence Training · Homeland Security · ATC Simulation · Transport Simulators · Industrial Process Simulation · Manufacturing Simulation · Mining Simulation · Oil & Gas Simulation · Energy Systems · Healthcare Simulation · Emergency Response · Urban Planning · Gaming Simulation · Aerospace · Defense · Homeland Security · Automotive · Engineering · Mining · Transport · Healthcare · Manufacturing · Gaming",
    image: "/assets/generated/service-vs.dim_800x500.jpg",
  },
  {
    icon: <Network className="w-7 h-7" />,
    title: "Digital Twins (DT)",
    desc: "Real-time virtual replicas of physical assets, systems, and processes — enabling predictive maintenance, performance optimization, and remote monitoring.",
    tag: "Real-time Synchronization · Predictive Maintenance · ML Anomaly Detection · Remote Monitoring · 3D Visualization · Performance Simulation · What-if Analysis · VR & AR Integration · Data Analytics · Role-based Access · Scalable Architecture · Industrial Equipment Monitoring · Smart Factory · Energy & Oil Gas · Aerospace Systems · Automotive & Transport · Infrastructure Management · Smart City · Healthcare Equipment · Mining Performance · Aerospace · Defense · Homeland Security · Automotive · Engineering · Mining · Transport · Healthcare · Manufacturing · Gaming",
    image: "/assets/generated/service-digitaltwin.dim_800x500.jpg",
  },
  {
    icon: <Brain className="w-7 h-7" />,
    title: "Artificial Intelligence (AI)",
    desc: "AI-powered solutions including intelligent bots for assistance, machine learning\u2013based object recognition, predictive analytics, intelligent automation, and data-driven decision-making across industries.",
    tag: "Machine Learning · Object Recognition · Computer Vision · Quality Inspection · Defect Detection · Predictive Analytics · AI Performance Analytics · Intelligent Chatbots · Virtual Assistants · Adaptive Learning · IoT Data Fusion · Digital Twin Enhancement · Secure AI Pipelines · VR/AR/MR Training · Predictive Maintenance · Field Service Assistance · Customer Support · Safety Monitoring · Aerospace · Defense · Homeland Security · Automotive · Engineering · Mining · Transport · Healthcare · Manufacturing · Gaming",
    image: "/assets/generated/service-ai.dim_800x500.jpg",
  },
];

export const PRODUCTS: Product[] = [
  {
    icon: <MapIcon className="w-5 h-5" />,
    name: "Trian3DBuilder",
    desc: "3D Terrain Development software",
    image: "/assets/generated/product-trian3dbuilder.dim_600x380.jpg",
  },
  {
    icon: <Box className="w-5 h-5" />,
    name: "REMO 3D",
    desc: "Specialized 3D modeling software for real-time visualization",
    image: "/assets/generated/product-remo3d.dim_600x380.jpg",
  },
  {
    icon: <Globe className="w-5 h-5" />,
    name: "Remoscape",
    desc: "3D landscape visualization and scene composition tool",
    image: "/assets/generated/product-remoscape.dim_600x380.jpg",
  },
  {
    icon: <Crosshair className="w-5 h-5" />,
    name: "SSG",
    desc: "War gaming and advanced simulation scenario creation platform",
    image: "/assets/generated/product-simax.dim_600x380.jpg",
  },
  {
    icon: <Cloud className="w-5 h-5" />,
    name: "SilverLining",
    desc: "Cloud and Sky rendering SDK",
    image: "/assets/generated/product-silverlining.dim_600x380.jpg",
  },
  {
    icon: <Waves className="w-5 h-5" />,
    name: "Triton",
    desc: "Ocean simulation SDK",
    image: "/assets/generated/product-triton.dim_600x380.jpg",
  },
  {
    icon: <Search className="w-5 h-5" />,
    name: "VIDERE",
    desc: "Virtual Design Review tool",
    image: "/assets/generated/product-videre.dim_600x380.jpg",
  },
  {
    icon: <ShieldCheck className="w-5 h-5" />,
    name: "VRSAFE",
    desc: "VR based Fire Safety Training tool",
    image: "/assets/generated/product-vrsafe.dim_600x380.jpg",
  },
  {
    icon: <Radio className="w-5 h-5" />,
    name: "AUGMENTOR",
    desc: "Remote Assistance Tool",
    image: "/assets/generated/product-augmentor.dim_600x380.jpg",
  },
  {
    icon: <Sofa className="w-5 h-5" />,
    name: "FARNISH",
    desc: "AR based Furniture Trial and Sales tool",
    image: "/assets/generated/product-farnish.dim_600x380.jpg",
  },
  {
    icon: <FileText className="w-5 h-5" />,
    name: "PRODOC",
    desc: "Interactive product document creator",
    image: "/assets/generated/product-prodoc.dim_600x380.jpg",
  },
  {
    icon: <ScanSearch className="w-5 h-5" />,
    name: "LAYAR",
    desc: "ML based AR tool",
    image: "/assets/generated/product-layar.dim_600x380.jpg",
  },
  {
    icon: <Bot className="w-5 h-5" />,
    name: "INTBOT",
    desc: "AI based Chatbot to assist users",
    image: "/assets/generated/product-intbot.dim_600x380.jpg",
  },
  {
    icon: <Paintbrush className="w-5 h-5" />,
    name: "PAINTX",
    desc: "VR based training tool for painters",
    image: "/assets/generated/product-paintx-car.dim_600x380.jpg",
  },
  {
    icon: <Gamepad2 className="w-5 h-5" />,
    name: "TORQUE",
    desc: "Multiplayer car stunt racing game",
    image: "/assets/generated/product-torque.dim_600x380.jpg",
  },
  {
    icon: <Users className="w-5 h-5" />,
    name: "COLLAB",
    desc: "Solution for collaborative virtual reality",
    image: "/assets/generated/product-collab.dim_600x380.jpg",
  },
];

export const INDUSTRIES: Industry[] = [
  {
    icon: <Plane className="w-7 h-7" />,
    name: "Aerospace",
    desc: "Flight simulation, mission training, and avionics visualization",
    image: "/assets/generated/industry-aerospace.dim_600x400.jpg",
  },
  {
    icon: <Shield className="w-7 h-7" />,
    name: "Defense",
    desc: "War gaming, tactical training, and defense simulation systems",
    image: "/assets/generated/industry-defense.dim_600x400.jpg",
  },
  {
    icon: <ShieldEllipsis className="w-7 h-7" />,
    name: "Homeland Security",
    desc: "Surveillance simulation, border security training, and crisis response systems",
    image: "/assets/generated/industry-homeland-security.dim_600x400.jpg",
  },
  {
    icon: <Car className="w-7 h-7" />,
    name: "Automotive",
    desc: "Design review, assembly training, and driver simulation",
    image: "/assets/generated/industry-automotive.dim_600x400.jpg",
  },
  {
    icon: <Wrench className="w-7 h-7" />,
    name: "Engineering",
    desc: "CAD visualization, maintenance training, and process simulation",
    image: "/assets/generated/industry-engineering.dim_600x400.jpg",
  },
  {
    icon: <HardHat className="w-7 h-7" />,
    name: "Mining",
    desc: "Safety training, underground navigation, and equipment simulation",
    image: "/assets/generated/industry-mining.dim_600x400.jpg",
  },
  {
    icon: <Train className="w-7 h-7" />,
    name: "Transport",
    desc: "Driver training, route simulation, and operational systems",
    image: "/assets/generated/industry-transport.dim_600x400.jpg",
  },
  {
    icon: <HeartPulse className="w-7 h-7" />,
    name: "Healthcare",
    desc: "Medical procedure training and patient care visualization",
    image: "/assets/generated/industry-healthcare-mri.dim_600x400.jpg",
    bannerImage:
      "/assets/generated/industry-healthcare-pharma.dim_1200x400.jpg",
  },
  {
    icon: <Factory className="w-7 h-7" />,
    name: "Manufacturing",
    desc: "AR-guided assembly, quality inspection simulation, and smart factory training",
    image: "/assets/generated/industry-manufacturing.dim_600x400.jpg",
  },
  {
    icon: <Gamepad2 className="w-7 h-7" />,
    name: "Gaming",
    desc: "Immersive game development, VR/AR gaming experiences, and multiplayer simulation",
    image: "/assets/generated/industry-gaming.dim_600x400.jpg",
    bannerImage: "/assets/generated/industry-gaming-racing.dim_1200x400.jpg",
  },
];

// Extended details for detail pages
export const SERVICE_DETAILS: Record<
  string,
  { features: string[]; industries: string[]; applicationAreas?: string[] }
> = {
  "virtual-reality-vr": {
    features: [
      "Development of 3D immersive, interactive, and simulation-based high-performance applications for training, sales and marketing, product demonstrations, enhanced product experiences, design reviews, ergonomic studies, gaming, and more",
      "Multi-user collaborative VR environments for team training, product reviews, and shared virtual experiences",
      "Real-time physics, interactions, and behavior modeling for high-fidelity and realistic simulations",
      "Scenario-based training modules with configurable environments and workflows",
      "Multiple VR modes: theatre mode, guided learning mode, practice mode, and assessment/test mode",
      "Performance analytics and trainee assessment dashboards with detailed reporting and insights",
      "Integration with hardware and IoT systems for simulator-based training and real-world equipment interfacing",
      "Digital Twin integration for system-level simulation, monitoring, and analysis",
      "AI-driven adaptive learning systems for personalized training and intelligent feedback",
      "Voice commands, gesture recognition, and intuitive interaction mechanisms",
      "High-quality 3D asset creation, optimization, and real-time rendering",
      "Localization and multi-language support for global deployments",
      "Secure deployment with user authentication, role-based access control, and data protection",
      "Support for large-scale simulation environments and complex system integration",
      "Custom UI/UX development for intuitive interaction and control",
      "Wide range of platforms supported: Windows, WebGL, iOS, Android, Meta (Oculus) Quest, HTC Vive, Pico, HP Reverb, Samsung Gear VR, Apple Vision Pro, and other leading VR devices",
      "Compatibility with custom hardware setups, including simulators, motion platforms, and control interfaces",
    ],
    applicationAreas: [
      "Aircraft systems operation and maintenance training",
      "ATC simulation and training",
      "Automotive, locomotive, and heavy vehicle operation and maintenance training",
      "Construction, mining, and agricultural equipment operation and maintenance training",
      "Rail, road, and water transport systems operation and maintenance training",
      "Healthcare and pharmaceutical equipment training",
      "Defense applications, including tank, ship, army, and navy systems training",
      "Weapon simulators for training",
      "Driving simulators for skill development and assessment",
      "Fire safety training (home, office, industrial, and public environments)",
      "Emergency response training",
      "Industrial safety and compliance training",
      "Industrial equipment usage and maintenance training",
      "Architectural walkthroughs and planning",
      "Immersive gaming and entertainment",
      "Many more evolving application areas",
    ],
    industries: [
      "Aerospace",
      "Defense",
      "Homeland Security",
      "Automotive",
      "Engineering",
      "Mining",
      "Transport",
      "Healthcare",
      "Manufacturing",
      "Gaming",
    ],
  },
  "augmented-reality-ar": {
    features: [
      "Marker-based and markerless AR solutions for maintenance, assembly, and operational guidance",
      "Object tracking and alignment for accurate interaction with real-world equipment",
      "Development of mobile AR applications for iOS and Android platforms",
      "AR-powered remote assistance with live expert guidance, annotations, and real-time collaboration",
      "Interactive AR instruction manuals and digital documentation for step-by-step guidance",
      "Product visualization and configuration for retail, e-commerce, and customer engagement",
      "Integration with enterprise systems (such as IoT platforms)",
      "Real-time data visualization overlays on physical equipment and environments",
      "3D model overlay and alignment with real-world objects for accurate guidance",
      "Cloud-based AR deployment for scalability and remote accessibility",
      "Wide range of platforms supported: Android, iOS, Windows, across mobile devices, tablets, and AR glasses such as RealWear, Vuzix and other popular AR glasses",
      "Multi-user collaborative AR environments for shared experiences and training",
      "Localization and multi-language support for global deployments",
      "Secure access and role-based controls for enterprise usage",
      "High-performance 2D and 3D content development and optimization for real-time rendering on mobile devices",
      "Custom UI/UX development for intuitive interaction and control",
      "Offline functionality for use in low or no connectivity environments",
    ],
    applicationAreas: [
      "Maintenance, repair, and operations (MRO) guidance for industrial equipment",
      "Assembly and disassembly assistance in manufacturing environments",
      "Field service and remote technical support",
      "Training and skill development for industrial and technical workforce",
      "Quality inspection and validation processes",
      "Product visualization and virtual try-before-you-buy experiences",
      "Retail and e-commerce interactive experiences",
      "Healthcare applications (equipment guidance, training, visualization)",
      "Pharmaceutical manufacturing and process training",
      "Construction and infrastructure visualization (on-site overlays, planning)",
      "Architecture and interior design visualization",
      "Logistics and warehouse operations (picking, navigation, optimization)",
      "Automotive service and maintenance guidance",
      "Aerospace and defense maintenance and training applications",
      "Tourism, education, and museum experiences",
      "Marketing campaigns and brand engagement experiences",
      "Smart city and urban planning visualization",
      "AR based games and entertainment",
      "Many more evolving application areas",
    ],
    industries: [
      "Aerospace",
      "Defense",
      "Homeland Security",
      "Automotive",
      "Engineering",
      "Mining",
      "Transport",
      "Healthcare",
      "Manufacturing",
      "Gaming",
    ],
  },
  "mixed-reality-mr": {
    features: [
      "Mixed Reality application development for enterprise and industrial use cases",
      "Spatial mapping and environment understanding for accurate placement of holographic content in real-world settings",
      "Holographic visualization of 3D models and data within physical environments",
      "Collaborative design reviews with real-time, remote stakeholder participation",
      "Hands-free MR workflows for field technicians, engineers, and operators",
      "Design visualization and validation",
      "Gesture-based and voice-controlled interfaces for intuitive and hands-free interaction",
      "Real-time data overlays on physical systems for monitoring and diagnostics",
      "Multi-user shared MR environments for collaborative training and operations",
      "Digital Twin integration for synchronized physical and virtual system interaction",
      "IoT integration for live data streaming and contextual visualization",
      "Step-by-step guided workflows for maintenance, assembly, and inspection tasks",
      "Remote expert assistance with live annotations and spatial guidance",
      "Object tracking and alignment for accurate interaction with real-world equipment",
      "Secure enterprise deployment with user authentication and role-based access",
      "Cloud connectivity for data synchronization, updates, and scalability",
      "Wide range of platforms supported: Microsoft HoloLens, Magic Leap, MR headsets and supporting platforms",
      "High-performance 2D and 3D content development and optimization for real-time rendering on MR devices",
      "Custom UI/UX development for intuitive interaction and control",
    ],
    applicationAreas: [
      "Industrial maintenance and repair (MRO) with hands-free guidance",
      "Assembly and disassembly workflows with real-time visual instructions",
      "Design reviews and virtual prototyping in real-world environments",
      "Manufacturing process visualization and optimization",
      "Quality inspection and validation using overlay-based comparisons",
      "Field service and remote technical assistance",
      "Training and skill development for technicians and engineers",
      "Aerospace and defense system maintenance and operations",
      "Automotive design, assembly, and service applications",
      "Healthcare applications (equipment guidance, surgical planning, training)",
      "Construction and infrastructure planning and visualization",
      "Energy, oil & gas, and utilities maintenance support",
      "Warehouse, logistics, and supply chain operations",
      "Product visualization and customer experience enhancement",
      "Safety training and hazard identification in real environments",
      "Smart factory and Industry 4.0 applications",
      "Research, education, and simulation environments",
      "MR based games and entertainment",
      "Many more evolving application areas",
    ],
    industries: [
      "Aerospace",
      "Defense",
      "Homeland Security",
      "Automotive",
      "Engineering",
      "Mining",
      "Transport",
      "Healthcare",
      "Manufacturing",
      "Gaming",
    ],
  },
  "visual-simulation-vs": {
    features: [
      "Development of high-quality, optimized 3D models for real-time simulation environments",
      "3D optimized terrain development, including geo-specific, geo-typic, and generic terrains",
      "Visual simulation application development for training, analysis, and decision support",
      "Desktop-based interactive learning applications for technical and operational training",
      "Desktop simulator development for various domain-specific applications",
      "Hardware-in-the-loop (HIL) simulator development, with integration of real-world physical controls and motion platforms for realistic simulation experiences",
      "Real-time rendering and visualization for high-fidelity simulation experiences",
      "Scenario-based simulation environments with configurable parameters and workflows",
      "Physics-based modeling and behavior simulation for realistic system interactions",
      "Multi-user and networked simulation environments for collaborative training and operations",
      "AI-driven simulation models for intelligent behavior and predictive analysis",
      "Data-driven simulation and analytics for performance evaluation and insights",
      "Support for large-scale environments and complex system simulations",
      "Digital Twin integration for system-level simulation and monitoring",
      "Custom UI/UX development for intuitive interaction and control",
      "High-performance optimization for real-time execution of complex simulations",
      "Secure and scalable deployment for enterprise and defense applications",
    ],
    applicationAreas: [
      "Aerospace, aviation, and space systems simulation (operations, maintenance, mission planning)",
      "Defense, army, navy, and homeland security training and mission simulation",
      "Weapon systems and combat simulation environments",
      "Air traffic control (ATC) and airport operations simulation",
      "Driver, vehicle, and transport system simulators (rail, road, marine, aviation)",
      "Industrial process simulation and operator training",
      "Manufacturing and assembly line simulation and optimization",
      "Mining operations and heavy equipment simulation",
      "Oil & gas exploration, drilling, and operations simulation",
      "Energy and utilities systems simulation (power plants, grid operations)",
      "Healthcare and pharmaceutical process and equipment simulation",
      "Engineering system design, validation, and performance analysis",
      "Emergency response and disaster management simulation",
      "Urban planning, infrastructure, and smart city simulations",
      "Gaming and entertainment simulation environments",
      "Research, education, and advanced simulation studies",
      "Many more evolving application areas",
    ],
    industries: [
      "Aerospace",
      "Defense",
      "Homeland Security",
      "Automotive",
      "Engineering",
      "Mining",
      "Transport",
      "Healthcare",
      "Manufacturing",
      "Gaming",
    ],
  },
  "digital-twins-dt": {
    features: [
      "Real-time synchronization between physical assets and their virtual counterparts for accurate monitoring and control",
      "Predictive maintenance using sensor data and ML-based anomaly detection to minimize downtime and optimize asset performance",
      "Remote monitoring dashboards with interactive 3D visualization for intuitive system insights",
      "Performance simulation and what-if scenario analysis for optimization and decision-making",
      "Integration with VR and AR technologies for interactive and immersive digital twin experiences",
      "Development of optimized visual content for high-performance, real-time applications",
      "Custom UI/UX design for intuitive interaction, control, and data visualization",
      "Data-driven analytics and reporting tools for performance tracking and insights",
      "Secure data handling and role-based access control for enterprise environments",
      "Scalable architecture to support large and complex systems",
    ],
    applicationAreas: [
      "Industrial equipment monitoring and predictive maintenance",
      "Manufacturing process optimization and smart factory applications",
      "Energy, oil & gas, and utilities asset management (power plants, grids, pipelines)",
      "Aerospace and defense systems monitoring and simulation",
      "Automotive and transport systems performance monitoring and optimization",
      "Infrastructure and smart city management (buildings, traffic, utilities)",
      "Healthcare and pharmaceutical equipment monitoring and process optimization",
      "Mining and heavy equipment performance tracking",
      "Training and simulation using real-world system data",
      "Many more evolving application areas",
    ],
    industries: [
      "Aerospace",
      "Defense",
      "Homeland Security",
      "Automotive",
      "Engineering",
      "Mining",
      "Transport",
      "Healthcare",
      "Manufacturing",
      "Gaming",
    ],
  },
  // keep old key for backward compat
  "digital-twins": {
    features: [
      "Real-time synchronization between physical assets and their virtual counterparts for accurate monitoring and control",
      "Predictive maintenance using sensor data and ML-based anomaly detection to minimize downtime and optimize asset performance",
      "Remote monitoring dashboards with interactive 3D visualization for intuitive system insights",
      "Performance simulation and what-if scenario analysis for optimization and decision-making",
      "Integration with VR and AR technologies for interactive and immersive digital twin experiences",
      "Development of optimized visual content for high-performance, real-time applications",
      "Custom UI/UX design for intuitive interaction, control, and data visualization",
      "Data-driven analytics and reporting tools for performance tracking and insights",
      "Secure data handling and role-based access control for enterprise environments",
      "Scalable architecture to support large and complex systems",
    ],
    applicationAreas: [
      "Industrial equipment monitoring and predictive maintenance",
      "Manufacturing process optimization and smart factory applications",
      "Energy, oil & gas, and utilities asset management (power plants, grids, pipelines)",
      "Aerospace and defense systems monitoring and simulation",
      "Automotive and transport systems performance monitoring and optimization",
      "Infrastructure and smart city management (buildings, traffic, utilities)",
      "Healthcare and pharmaceutical equipment monitoring and process optimization",
      "Mining and heavy equipment performance tracking",
      "Training and simulation using real-world system data",
      "Many more evolving application areas",
    ],
    industries: [
      "Aerospace",
      "Defense",
      "Homeland Security",
      "Automotive",
      "Engineering",
      "Mining",
      "Transport",
      "Healthcare",
      "Manufacturing",
      "Gaming",
    ],
  },
  "artificial-intelligence-ai": {
    features: [
      "Machine Learning-based object recognition and classification for real-time identification and tracking",
      "Computer Vision integration based quality inspection, defect detection, and maintenance support",
      "Predictive analytics for equipment failure detection and preventive maintenance",
      "AI-powered performance analytics for measuring training effectiveness and user behavior insights",
      "Intelligent chatbots and virtual assistants for guidance, customer interaction, and technical support",
      "AI-driven adaptive learning systems for personalized training experiences in VR/AR/MR/VS environments",
      "Data fusion from IoT sensors and enterprise systems for intelligent decision-making",
      "AI-driven digital twin enhancement for predictive modeling and system optimization",
      "Secure AI pipelines with data privacy, access control, and compliance",
    ],
    applicationAreas: [
      "AI-enhanced VR/AR/MR training systems with adaptive learning and real-time feedback",
      "Predictive maintenance for industrial equipment, vehicles, and infrastructure",
      "Field service and remote assistance with AI-guided troubleshooting",
      "Customer support using intelligent chatbots and virtual assistants",
      "Safety equipment monitoring and compliance confirmation",
      "Many more evolving application areas",
    ],
    industries: [
      "Aerospace",
      "Defense",
      "Homeland Security",
      "Automotive",
      "Engineering",
      "Mining",
      "Transport",
      "Healthcare",
      "Manufacturing",
      "Gaming",
    ],
  },
};

export const PRODUCT_DETAILS: Record<
  string,
  {
    features: string[];
    highlights?: string[];
    applicationAreas?: string[];
    overviewParagraph?: string;
  }
> = {
  trian3dbuilder: {
    overviewParagraph:
      "Trian3DBuilder is a powerful 3D terrain and environment generation platform designed for creating high-quality, real-time simulation databases. It enables users to generate large-scale, highly detailed terrains from real-world data with a high level of automation. The platform combines flexibility, performance, and ease of use to efficiently build complex virtual environments for simulation, training, gaming, and engineering applications.",
    features: [
      "Complete terrain generation solution for building large-scale simulation environments",
      "Automated terrain generation from real-world GIS data (OpenStreetMap, raster, vector, imagery)",
      "Creation of geo-specific, geo-typical, and generic terrains",
      "Development of high-detail, real-time optimized environments",
      "Ability to generate complete ecosystems, including roads and advanced road networks, railways, buildings, airports, ports, and landscapes, runways, taxiways, and airport lighting systems",
      "Access to 20,000+ pre-built airport datasets",
      "Advanced Roads Module for detailed road network generation",
      "Sensor Module for simulation-specific requirements",
      "Built-in libraries of models and textures for faster development",
      "High level of automation with project wizards for quick setup",
      "Procedural terrain generation and automatic object placement",
      "Intuitive 2D/3D WYSIWYG editing for easy modification and visualization",
      "Integrated 3D viewer for validation and preview",
      "Support for multiple data formats with automatic rule-based assignment",
      "Native OpenSceneGraph (OSG) support",
      "Export support for OpenFlight, MetaFlight, VBS2, GDB, FBX, OBJ, Collada, OpenDrive, Steel Beasts Pro",
      "Scalable architecture supporting very large databases with Level of Detail (LOD) management and streaming/paging capabilities",
      "High-performance processing with multi-CPU support",
      "Customization and extensibility via SDK, plugins, and scripting",
      "Workflow optimization with intelligent updates and fast rebuilds",
      "Designed to be user-friendly for efficient terrain generation workflows",
    ],
    applicationAreas: [
      "Flight simulation and airport environment modeling",
      "Defense and mission simulation environments",
      "Automotive and autonomous driving simulation",
      "Maritime and naval simulation",
      "Urban planning and smart city visualization",
      "Infrastructure and engineering visualization",
      "Gaming and serious games environments",
      "Geospatial analysis and terrain visualization",
      "Training simulators across multiple domains",
      "Any application requiring large-scale, realistic terrain generation",
    ],
  },
  "remo-3d": {
    overviewParagraph:
      "Remo 3D is a specialized 3D modeling software for real-time visualization, widely used in simulation, virtual reality, and defense applications. Unlike conventional modeling tools focused on offline rendering, Remo 3D is designed to create and optimize models for real-time performance, making it ideal for simulators, training systems, and interactive environments. The platform combines flexibility, precision, and efficiency to support the development of high-performance visual databases.",
    features: [
      "Creation and modification of 3D models optimized for real-time applications",
      "Scene graph-based modeling approach for structured and efficient model management",
      "Native support for OpenFlight® file format with extensive import/export capabilities",
      "Supports a wide range of import, export, and texture file formats",
      "Advanced simulation-specific features: Level-of-Detail (LOD) management for performance optimization, Degree-of-Freedom (DOF) node editing for dynamic simulations, support for Switch nodes, Light Points, and other simulation elements",
      "Real-time rendering and visualization capabilities",
      "Wide range of visualization and analysis tools",
      "WYSIWYG 3D model view for intuitive editing and validation",
      "Powerful geometry editing tools (transformations, snapping, selection, etc.)",
      "Multiple viewports with customizable configurations",
      "Efficient scene graph hierarchy management",
      "Designed for handling large-scale and complex models",
      "High-performance workflows with real-time characteristics",
      "Automation of repetitive tasks through scripting and tools",
      "User-friendly interface for efficient modeling workflows",
      "Multi-OS support (Windows and Linux environments)",
    ],
    applicationAreas: [
      "Defense and military simulation systems",
      "Flight, naval, and vehicle simulators",
      "Visual database creation for simulation environments",
      "Gaming and real-time interactive environments",
      "Digital twin and engineering visualization",
      "Training systems for operations and maintenance",
      "Urban, terrain, and infrastructure visualization",
      "Any application requiring optimized real-time 3D models",
    ],
  },
  remoscape: {
    overviewParagraph:
      "Remoscape is a powerful terrain and environment generation software designed for creating large-scale, high-performance visual databases for simulation and real-time applications. It enables efficient generation, editing, and optimization of terrains and environments, making it well-suited for defense, aerospace, training, and gaming applications. Remoscape focuses on delivering scalable, realistic, and performance-optimized environments for simulation systems.",
    features: [
      "Creation of large-scale terrains and environments optimized for real-time performance",
      "Support for geo-specific, geo-typical, and generic terrain generation",
      "Integration of GIS data, imagery, and elevation data (DTED) for accurate terrain modeling",
      "Automated terrain generation workflows for faster environment creation",
      "Advanced terrain editing and refinement tools",
      "Support for multi-resolution terrain (LOD) for performance optimization",
      "Efficient handling of large databases and tiled environments",
      "Seamless integration with REMO 3D for model placement and scene creation",
      "Real-time preview and visualization of terrains and environments",
      "Ability to generate roads, rivers, vegetation, and other environmental features",
      "Support for multiple output formats compatible with simulation and game engines",
      "Scalable architecture for handling complex and extensive simulation environments",
      "Tools for terrain texturing and material management",
      "High-performance optimization for simulation and training applications",
    ],
    applicationAreas: [
      "Defense and military simulation environments (land, air, and naval domains)",
      "Flight simulation and aerospace training systems",
      "Mission planning and rehearsal environments",
      "Autonomous vehicle and driving simulation",
      "Naval and maritime simulation environments",
      "Urban planning and smart city visualization",
      "Infrastructure and engineering visualization",
      "Gaming and real-time interactive environments",
      "Training simulators across industrial and operational domains",
      "Any application requiring large-scale, realistic terrain and environment generation",
    ],
  },
  ssg: {
    overviewParagraph:
      "SSG (Smart Scenario Generator) is an advanced war gaming and simulation platform designed to create, manage, and execute high-fidelity simulation scenarios for training, mission planning, and analysis. It enables users to build complex, dynamic, and realistic war gaming scenarios with ease, supporting a wide range of applications across defense, aerospace, and other simulation-driven industries. The platform focuses on flexibility, scalability, and efficient scenario generation for real-time environments.",
    features: [
      "Comprehensive Simulation Framework: scenario preparation, execution, monitoring, evaluation, and debriefing; supports Live, Virtual, and Constructive (LVC) simulation environments; high-fidelity, multi-domain simulation (land, air, and sea)",
      "Large-Scale Distributed Simulation: supports simulation of thousands to millions of entities; distributed real-time simulation with dynamic load balancing; scalable architecture for small to large simulation exercises",
      "Technical Knowledgebase Editor (TKE): define platforms, systems, and technical features; create custom entities (aircraft, ships, radars, missile systems, etc.); extend and add new capabilities without complex programming",
      "Platform & Environment Modeling: advanced modeling of platforms and operational systems; integration with terrain databases and geographic environments; realistic battlespace representation",
      "Sensor & Electronic Warfare Simulation: simulation of radars, IR/FLIR, NVG, and surveillance systems; electronic warfare capabilities including radar and communication jamming, spoofing and decoy deployment; high-fidelity parametric sensor modeling",
      "Weapon & Engagement Simulation: simulation of missiles, artillery, guns, rockets, bombs, and charges; realistic engagement modeling based on platform capabilities",
      "Autonomous CGF & Behavior Modeling: autonomous Computer Generated Forces (CGF) for large-scale simulations; Behavior Editor and knowledgebase for defining operational logic; user-defined warfare techniques and doctrines (state-machine-based); adaptive, reactive, and AI-driven behavior modeling; automatic mission planning capabilities",
      "Command, Control & Force Management: hierarchical force structure (commanders and subordinates); tactical situation awareness and decision-making simulation; communication and datalink modeling",
      "Scenario Monitoring & Control: dedicated operator consoles for real-time control; control over platforms, environment, sensors, and communications; role-based access (Blue/Red/Instructor forces)",
      "Evaluation, Debriefing & What-If Analysis: performance monitoring (attrition, logistics, detection, communication); full scenario recording and replay; event-based analysis and visualization; what-if analysis for alternative decision evaluation",
      "Open Architecture & Integration: open, modular architecture based on distributed multi-agent systems; integration with C2/C3I systems and external simulation engines; interoperability with standard protocols (e.g., DIS/HLA); supports custom development and model extensions",
      "Key Advantages: open and modular system architecture; fully distributed and highly scalable; reusable simulation models and knowledgebases; easy integration with external systems; enables domain experts to configure scenarios without coding",
    ],
    applicationAreas: [
      "Naval tactical trainers and naval wargaming systems",
      "Embedded UAV and platform trainers",
      "Urban simulation environments and concept development laboratories",
      "Integration and validation laboratories",
      "Large-scale wargaming and strategic analysis",
      "Distributed tactical and mission training systems",
      "Joint and multi-domain operations training",
      "Command and Control (C2/C3I) system testing and validation",
      "Mission planning, rehearsal, and validation",
      "Electronic warfare training and analysis",
      "Autonomous systems and unmanned vehicle simulation",
      "Homeland security and surveillance scenario planning",
      "Research, development, and system validation",
      "Any domain requiring structured, scenario-driven simulation, training, and analysis",
    ],
  },
  silverlining: {
    overviewParagraph:
      "SilverLining is a high-performance real-time sky and weather simulation SDK designed to generate realistic clouds, atmosphere, and environmental effects for simulation, gaming, and visualization applications. It enables developers to create dynamic and immersive outdoor environments with physically based rendering of sky, lighting, and weather conditions, optimized for real-time performance.",
    features: [
      "Real-time 3D volumetric cloud rendering with realistic lighting and shadows",
      "Support for multiple cloud types: cumulus, stratus, cirrus, cumulonimbus, and layered cloud formations",
      "Dynamic weather simulation including cloud movement, wind effects, and atmospheric changes",
      "Physically based sky and atmospheric scattering models for realistic daylight, sunrise, and sunset effects",
      "Accurate sun, moon, stars, and celestial lighting simulation",
      "Weather transitions and time-of-day control for dynamic environments",
      "Realistic fog, haze, and visibility effects",
      "High-performance rendering optimized for real-time simulation and large environments",
      "Seamless integration with OpenGL, DirectX, Vulkan, and major 3D engines",
      "Support for VR and simulation systems",
      "Configurable cloud density, altitude, coverage, and lighting conditions",
      "Scalable from desktop applications to high-end simulators",
      "Easy-to-use API for integration and customization",
    ],
    applicationAreas: [
      "Flight simulation and aerospace training systems",
      "Defense and mission simulation environments",
      "Maritime and naval simulation",
      "Automotive and autonomous driving simulation",
      "Gaming and immersive virtual environments",
      "Visual simulation and digital twin environments",
      "Weather visualization and environmental studies",
      "VR/AR/MR-based training and visualization applications",
      "Film, animation, and real-time visualization projects",
      "Any application requiring realistic outdoor environmental simulation",
    ],
  },
  triton: {
    overviewParagraph:
      "Triton is a high-performance real-time ocean and water rendering SDK designed to simulate realistic water surfaces and marine environments for simulation, gaming, and visualization applications. It enables the creation of dynamic oceans, seas, and inland water bodies with physically based behavior, optimized for real-time performance and seamless integration with simulation systems.",
    features: [
      "Real-time ocean and water surface simulation with physically based wave dynamics",
      "Support for deep ocean, coastal, and inland water bodies (lakes, rivers)",
      "Realistic wave generation using spectral wave models",
      "Dynamic water interaction with wind, objects, and environment",
      "Accurate reflections, refractions, and light scattering effects",
      "Simulation of foam, spray, and wake effects for vessels and moving objects",
      "Configurable sea states and environmental conditions",
      "Seamless integration with sky and weather systems (e.g., SilverLining)",
      "High-performance rendering optimized for real-time simulation environments",
      "Support for large-scale ocean environments",
      "Easy integration with OpenGL, DirectX, Vulkan, and major 3D engines",
      "Scalable across desktop, simulation systems, and VR environments",
      "Flexible API for customization and control",
    ],
    applicationAreas: [
      "Naval and maritime simulation systems",
      "Defense and mission simulation environments",
      "Ship navigation and training simulators",
      "Offshore and oil & gas simulation and visualization",
      "Coastal and environmental studies",
      "Autonomous marine vehicle simulation",
      "Gaming and immersive virtual environments",
      "VR/AR/MR-based simulation and training applications",
      "Digital twin environments involving water systems",
      "Film, animation, and real-time visualization projects",
      "Any application requiring realistic water and ocean simulation",
    ],
  },
  videre: {
    overviewParagraph:
      "VIDERE (Virtual Design Reviewer) is an advanced virtual design review platform that enables immersive, interactive visualization and analysis of engineering designs in a real-time simulation environment. It allows teams to evaluate, validate, and optimize designs before physical prototyping, reducing development time, cost, and errors. With physics-based interactions and collaborative capabilities, VIDERE enhances decision-making across the product lifecycle.",
    features: [
      "Real-time, interactive 3D design visualization",
      "Scale up / scale down models dynamically",
      "Rotate models along X, Y, and Z axes",
      "Move models along any axis for detailed inspection",
      "Real-time simulation-based collision detection",
      "Physics-enabled interactions and collision response",
      "Collision logging for detailed post-analysis",
      "Ergonomics study for human interaction and usability",
      "Exploded view",
      "Cross-sectional views in any plane and at any angle",
      "Freeze and unfreeze section views as required",
      "Real-time measurements",
      "Convert CAD models into optimized 3D assets",
      "Add new models to the virtual environment at runtime",
      "Customizable to meet project-specific requirements",
    ],
    applicationAreas: [
      "Automotive & Aerospace: design validation, assembly verification, and collision analysis",
      "Manufacturing & Engineering: product design reviews, process planning, and simulation",
      "Architecture & Construction: virtual walkthroughs and structural design validation",
      "Defense & Training: simulation-based design evaluation and mission planning",
      "Healthcare & Ergonomics: human-factor analysis and usability studies",
      "Industrial Design: concept visualization and rapid design iteration",
    ],
  },
  vrsafe: {
    overviewParagraph:
      "VRSAFE is an immersive virtual reality (VR) fire safety training solution designed to prepare individuals and teams for real-world fire emergencies. By simulating realistic fire scenarios in a safe and controlled environment, VRSAFE enables users to practice critical response actions, improve situational awareness, and build confidence without any risk. It enhances training effectiveness through experiential learning and measurable performance insights.",
    features: [
      "Immersive VR-based fire safety training scenarios",
      "Realistic fire behavior simulation with smoke and heat effects",
      "Highly engaging, real-life emergency environments",
      "Interactive fire extinguisher operation",
      "Guided and unguided evacuation training scenarios",
      "Scenario-based decision-making practice",
      "Real-time performance tracking",
      "Detailed trainee assessment and reporting",
      "Feedback-driven learning and improvement",
      "Customizable building layouts and fire scenarios",
      "Adaptable for different industries and safety protocols",
      "Compatible with all leading VR headsets, web and desktop",
    ],
    applicationAreas: [
      "Corporate Offices & IT Parks: employee fire safety training and evacuation preparedness",
      "Manufacturing & Industrial Facilities: hazard awareness and emergency response drills",
      "Educational Institutions: safety training for students and staff",
      "Healthcare Facilities: emergency evacuation and safety compliance training",
      "Hospitality & Retail: staff preparedness for fire incidents in public spaces",
      "Government & Public Safety Organizations: fire safety awareness and disaster preparedness programs",
    ],
  },
  augmentor: {
    overviewParagraph:
      "AUGMENTOR is an advanced augmented reality (AR) remote assistance platform designed to support field technicians with real-time expert guidance. By combining live video, AR annotations, and interactive workflows, AUGMENTOR enables faster issue resolution, reduces downtime, and minimizes the need for on-site expert presence. It empowers organizations to enhance operational efficiency and deliver seamless maintenance and support services across distributed locations.",
    features: [
      "Real-time AR-based remote assistance for field technicians",
      "Live video streaming between field personnel and remote experts",
      "Instant visual collaboration for faster troubleshooting",
      "On-screen annotation and markup in the real-world view",
      "Highlight components and guide actions visually",
      "Improve clarity and reduce communication errors",
      "Step-by-step guided maintenance and repair workflows",
      "Reduced dependency on highly experienced personnel",
      "Integration with enterprise ticketing systems",
      "Access to knowledge management systems and documentation",
      "Seamless workflow from issue reporting to resolution",
      "Access to preloaded instructions and workflows offline",
      "Compatible with smartphones, tablets, and AR glasses",
    ],
    applicationAreas: [
      "Manufacturing & Industrial Maintenance: equipment troubleshooting, preventive maintenance, and repairs",
      "Utilities & Energy: field service support for power plants, oil & gas, and infrastructure",
      "Telecommunications: network installation, inspection, and fault resolution",
      "Automotive & Heavy Equipment: service, diagnostics, and remote expert assistance",
      "Healthcare Equipment Support: maintenance and servicing of medical devices",
      "Facility Management: building systems maintenance and operational support",
    ],
  },
  farnish: {
    overviewParagraph:
      "FARNISH is an augmented reality (AR) platform that enables users to visualize and evaluate furniture in their real-world spaces before making a purchase. By overlaying true-to-scale 3D furniture models into a user's environment, FARNISH enhances buying confidence, reduces uncertainty, and improves the overall shopping experience. It bridges the gap between online browsing and in-store decision-making, driving higher customer engagement and sales conversions.",
    features: [
      "Place furniture in real environments using AR",
      "True-to-scale visualization for accurate spatial understanding",
      "Real-time rendering of products in user spaces",
      "Move, rotate, and reposition furniture easily",
      "View products from different angles and perspectives",
      "Explore multiple variants such as colors, materials, and finishes",
      "Assess fit, layout, and aesthetics before purchase",
      "Avoid size mismatches and design conflicts",
      "Improve interior planning decisions",
      "Seamless integration with digital product catalogs",
      "Access detailed product information within the AR experience",
      "Easy browsing and selection of furniture items",
      "Direct purchase or inquiry options within the platform",
      "Share AR views with family or decision-makers",
      "Enhance customer engagement and conversion rates",
      "Compatible with smartphones, tablets, and AR-enabled devices",
      "Accessible anytime, anywhere",
      "Customizable for different brands and retail requirements",
      "Scalable for large product inventories",
    ],
    applicationAreas: [
      "Furniture Retail & E-commerce: virtual try-before-you-buy experience for customers",
      "Interior Design: visualization and planning of home and office spaces",
      "Real Estate & Property Staging: virtual furnishing of empty spaces for better presentation",
      "Home Improvement & Decor: selection and placement of furniture and decor items",
      "Retail Showrooms: enhanced in-store digital experience for customers",
    ],
  },
  prodoc: {
    overviewParagraph:
      "PRODOC is an interactive documentation platform that transforms traditional product manuals into engaging, visual, and easy-to-understand digital experiences. It enables users to create step-by-step instructions using 3D content, animations, and multimedia elements, improving clarity and usability over static documents. With no coding required, cross-platform support, and optional augmented reality capabilities, PRODOC simplifies the creation, management, and delivery of technical documentation for training, maintenance, and product communication.",
    features: [
      "Create step-by-step visual instructions with basic animations and views",
      "Convert CAD models into optimized 3D content",
      "Add text and visual guidance for better clarity",
      "Use interactive elements such as hotspots for explanations",
      "Add audio, video and graphical content",
      "No coding required for creating and managing manuals",
      "Support for offline and web-based usage",
      "Supported platforms: Windows, Android, iOS, and Web",
      "Export content for easy sharing and deployment",
      "Can have Augmented Reality as add-on capability",
      "Continuously evolving with new features",
      "Can be customized to meet specific enterprise requirements",
      "Simplifies complex technical documentation with interactive content",
      "Improves clarity compared to static manuals",
      "Supports training, maintenance, product demonstration, marketing use cases",
      "Focused on ease of use and practical workflows",
    ],
    applicationAreas: [
      "Service and maintenance documentation for field technicians",
      "Assembly and disassembly manuals for industrial equipment",
      "Product demonstration and marketing content",
      "Training materials for operational and safety procedures",
      "Interactive product experience for customers",
    ],
  },
  layar: {
    overviewParagraph:
      "LAYAR is an intelligent augmented reality (AR) platform powered by machine learning (ML) that enables seamless interaction between the physical and digital worlds. By recognizing real-world objects and environments, LAYAR dynamically triggers contextual AR overlays, delivering enriched, interactive experiences. It enhances visualization, automation, and user engagement across a wide range of applications by making AR smarter and more responsive.",
    features: [
      "ML-based object recognition and tracking",
      "Accurate identification of real-world objects and surfaces",
      "Continuous learning for improved recognition performance",
      "Trigger AR content based on recognized objects",
      "Dynamic and context-aware information display",
      "Rich multimedia overlays including text, images, and 3D content",
      "Instant AR response with minimal latency",
      "Interactive overlays for enhanced user engagement",
      "Manage and update AR content dynamically",
      "Compatible with smartphones, tablets, and AR-enabled devices",
      "Tailored solutions based on specific industry requirements",
      "Flexible architecture for adding new use cases",
    ],
    applicationAreas: [
      "Retail & Marketing: product recognition with interactive AR promotions and information",
      "Manufacturing & Maintenance: equipment identification with guided AR instructions",
      "Education & Training: interactive learning through object-based AR experiences",
      "Healthcare: medical training and equipment visualization using AR overlays",
      "Museums & Exhibitions: artifact recognition with immersive storytelling and information",
      "Logistics & Warehousing: package identification, tracking, and workflow guidance",
    ],
  },
  intbot: {
    overviewParagraph:
      "INTBOT is an AI-powered intelligent chatbot designed to assist users with real-time information and guidance. Leveraging advanced natural language processing (NLP) and machine learning capabilities, INTBOT delivers accurate, context-aware responses. It enhances user experience, reduces response time, and improves operational efficiency by providing instant, reliable support.",
    features: [
      "AI-powered chatbot for product and service assistance",
      "Natural language understanding for human-like interactions",
      "Context-aware responses for meaningful conversations",
      "Continuous learning to improve accuracy over time",
      "Instant responses to user queries anytime",
      "Reduced dependency on manual support teams",
      "Scalable to handle high volumes of interactions",
      "Deployable across websites, and mobile apps",
      "Integration with knowledge bases, FAQs, and enterprise systems",
      "Accurate and consistent information delivery",
      "Automate routine tasks such as query resolution, and requests",
      "Generate insights for continuous improvement",
      "Tailored to specific business requirements",
    ],
    applicationAreas: [
      "Customer Support & Service: automated query handling and customer assistance",
      "Enterprise & IT Helpdesk: internal support for employees and IT services",
      "Healthcare: patient engagement, appointment assistance, and FAQs",
      "Banking & Financial Services: customer queries, transaction assistance, and support",
      "Education: student support, admissions guidance, and information access",
      "E-commerce & Retail: product recommendations, order tracking, and customer engagement",
    ],
  },
  paintx: {
    overviewParagraph:
      "PAINTX is an immersive virtual reality (VR) training solution designed to train painters in automotive and industrial applications within a safe, controlled, and highly realistic environment. It enables users to practice painting techniques, understand surface preparation, and optimize paint application without material wastage or safety risks. By combining simulation with hands-on virtual practice, PAINTX enhances skill development, consistency, and overall training efficiency.",
    features: [
      "VR-based paint application training for automotive and industrial use",
      "Realistic painting scenarios in a virtual workspace",
      "Safe training without material consumption or environmental hazards",
      "Realistic spray gun simulation",
      "Practice across different surfaces and geometries",
      "Coverage analysis and defect detection for quality training",
      "Visual feedback on paint thickness, uniformity, and missed areas",
      "Helps improve precision and finishing standards",
      "Performance metrics and trainee progress tracking",
      "Real-time monitoring and detailed evaluation reports",
      "Identify skill gaps and improvement areas",
      "Customizable environments and training modules",
      "Adaptable for different industry requirements",
      "Compatible with all leading VR headsets",
      "Supports scalable deployment across training centers",
    ],
    applicationAreas: [
      "Automotive Industry: vehicle body painting, refinishing, and quality control training",
      "Manufacturing & Industrial Coating: machinery, components, and equipment painting training",
      "Aerospace: precision coating and surface finishing applications",
      "Construction & Infrastructure: surface treatment and protective coating training",
      "Vocational Training Institutes: skill development programs for painters and technicians",
      "Industrial Training Centers: standardized and scalable workforce training",
    ],
  },
  torque: {
    overviewParagraph:
      "TORQUE is a high-energy multiplayer car stunt racing game designed to deliver thrilling, fast-paced racing experiences with a focus on extreme stunts and competitive gameplay. Combining realistic vehicle physics with dynamic environments, TORQUE allows players to race, perform daring stunts, and compete with others in real time. It offers an engaging mix of skill and speed, making it ideal for both casual gamers and competitive players.",
    features: [
      "Multiplayer car stunt racing with real-time physics",
      "Customizable vehicles and stunt tracks",
      "Competitive leaderboards and tournament modes",
      "Cross-platform multiplayer support",
      "High-fidelity 3D graphics with dynamic lighting",
      "Regular content updates with new cars and tracks",
    ],
    highlights: [
      "Real-time physics engine",
      "Multiplayer support",
      "Competitive leaderboards",
      "Dynamic 3D graphics",
    ],
  },
  collab: {
    overviewParagraph:
      "COLLAB is a powerful collaborative virtual reality (VR) framework designed to enable multiple users to interact, communicate, and work together in a shared immersive environment. It facilitates real-time collaboration across geographically distributed teams, allowing users to visualize, review, and manipulate digital content as if they were in the same physical space. COLLAB enhances teamwork, decision-making, and productivity through immersive and interactive experiences.",
    features: [
      "Real-time interaction between multiple users in a shared VR environment",
      "Support for geographically distributed teams",
      "Synchronized actions and shared experiences",
      "Voice communication and avatar-based presence",
      "Natural interactions for discussions and collaboration",
      "Enhanced sense of co-presence",
      "View, move, rotate, and scale 3D models collaboratively",
      "Real-time updates visible to all participants",
      "Shared control for design review and analysis",
      "Compatible with leading VR headsets and desktop-based systems",
      "Enables participation across different device types",
      "Adaptable to various industries and use cases",
      "Scalable from small team meetings to large collaborative sessions",
    ],
    applicationAreas: [
      "Design & Engineering Reviews: collaborative evaluation of 3D models and prototypes",
      "Architecture, Engineering & Construction (AEC): virtual walkthroughs and team-based project reviews",
      "Manufacturing & Product Development: cross-functional collaboration for design and production planning",
      "Training & Education: interactive group learning and simulation-based training",
      "Healthcare: collaborative medical training and procedure planning",
      "Remote Collaboration & Meetings: virtual meetings and discussions in immersive environments",
    ],
  },
};

export const INDUSTRY_SOLUTIONS: Record<
  string,
  {
    services: string[];
    products: string[];
    applicationAreas?: ApplicationAreaEntry[];
  }
> = {
  aerospace: {
    services: [
      "Virtual Reality (VR)",
      "Augmented Reality (AR)",
      "Mixed Reality (MR)",
      "Visual Simulation (VS)",
      "Digital Twins (DT)",
      "Artificial Intelligence (AI)",
    ],
    products: [
      "Trian3DBuilder",
      "SilverLining",
      "Triton",
      "VIDERE",
      "SSG",
      "REMO 3D",
      "AUGMENTOR",
      "PRODOC",
      "INTBOT",
    ],
    applicationAreas: [
      "Aircraft systems operation and maintenance training",
      "Flight simulation and aircrew training",
      "Mission planning and rehearsal simulation",
      "Avionics and instrument procedure training",
      "Air traffic control (ATC) simulation",
      "Virtual cockpit familiarization and procedural training",
      "UAV/UAS simulation and operator training",
      "Radar, sensor, and surveillance simulation",
      "Ground operations and airport logistics simulation",
      "Combat simulation, and war gaming scenarios",
      "Real-time maintenance guidance with AR overlays",
      "AR-assisted inspection, troubleshooting, and validation",
      "Interactive and AR capable technical manuals",
      "Remote assistance for field technicians",
      "Guided assembly and installation procedures",
      "Immersive design review of systems",
      "Virtual prototyping and human factor (ergonomics) studies",
      "Digital twin monitoring for aircraft and systems",
      "Real-time performance tracking and diagnostics",
      "Simulation of operational scenarios for optimization",
      "AI-driven predictive maintenance and intelligent diagnostics",
      "AI-based training evaluation and performance tracking",
      "Automated analysis of flight and operational data",
    ],
  },
  defense: {
    services: [
      "Virtual Reality (VR)",
      "Augmented Reality (AR)",
      "Mixed Reality (MR)",
      "Visual Simulation (VS)",
      "Digital Twins (DT)",
      "Artificial Intelligence (AI)",
    ],
    products: [
      "Trian3DBuilder",
      "SSG",
      "SilverLining",
      "Triton",
      "REMO 3D",
      "VIDERE",
      "VRSAFE",
      "AUGMENTOR",
      "PRODOC",
    ],
    applicationAreas: [
      "Weapon handling and operational training",
      "Soldier training and immersive combat simulation",
      "Vehicle and equipment operation training",
      "Emergency response training",
      "Virtual boot camps and tactical drills",
      "Maintenance training for defense equipment and systems",
      "Human factor and ergonomics studies for defense systems",
      "Real-time battlefield information overlay and situational awareness",
      "AR-based maintenance, repair guidance, and troubleshooting",
      "Remote assistance for field personnel and technicians",
      "Step-by-step operational instructions and digital manuals",
      "Multi-user immersive training and coordination exercises",
      "Advanced visualization for decision-making and planning",
      "Battlefield and combat simulation",
      "Radar, sensor, and surveillance simulation",
      "Mission rehearsal and war-gaming scenarios",
      "Terrain, environment, and threat simulation",
      "Command and control (C2) system simulation",
      "Digital twin monitoring of defense equipment and systems",
      "Predictive maintenance for mission-critical assets",
      "Simulation of operational scenarios for readiness",
      "AI-driven training evaluation and performance tracking",
      "Analytics and continuous improvement from operational data",
    ],
  },
  "homeland-security": {
    services: [
      "Virtual Reality (VR)",
      "Augmented Reality (AR)",
      "Mixed Reality (MR)",
      "Visual Simulation (VS)",
      "Digital Twins (DT)",
      "Artificial Intelligence (AI)",
    ],
    products: [
      "SSG",
      "SilverLining",
      "VIDERE",
      "VRSAFE",
      "Trian3DBuilder",
      "INTBOT",
      "AUGMENTOR",
    ],
    applicationAreas: [
      "Weapon operational training and maintenance",
      "Fire safety and evacuation training",
      "Security personnel training and assessment",
      "Command and control system training and operations",
      "Real-time situational awareness with AR overlays",
      "Remote assistance for security personnel",
      "Simulation of emergency scenarios for preparedness planning",
      "Collaborative emergency planning and simulation exercises",
      "Multi-agency coordination in shared immersive environments",
      "Border security and surveillance training",
      "Threat detection and response simulation",
      "Digital twin models of critical infrastructure for monitoring",
      "Real-time tracking and analysis of systems and environments",
      "Integration with knowledge bases for quick decision support",
      "Analytics and insights for improving response efficiency",
    ],
  },
  automotive: {
    services: [
      "Virtual Reality (VR)",
      "Augmented Reality (AR)",
      "Mixed Reality (MR)",
      "Visual Simulation (VS)",
      "Digital Twins (DT)",
      "Artificial Intelligence (AI)",
    ],
    products: [
      "VIDERE",
      "PAINTX",
      "PRODOC",
      "AUGMENTOR",
      "LAYAR",
      "INTBOT",
      "FARNISH",
    ],
    applicationAreas: [
      "Vehicle design review and visualization",
      "Assembly and manufacturing process training",
      "Driver training and simulation",
      "Paint application and quality training",
      "Product launch and marketing visualization",
      "Digital twin monitoring for vehicle systems",
      "AR-guided maintenance and service operations",
      "Virtual prototyping and ergonomics (human factor) studies",
      "Factory layout planning and production line simulation",
      "Quality inspection and defect detection",
      "Service technician training with interactive guidance",
      "Remote assistance for diagnostics and repairs",
      "Autonomous vehicle simulation and testing",
      "Dealership training and customer experience enhancement",
      "Interactive 3D product configurators for sales",
      "AI-powered chatbot support for customer queries and service assistance",
      "AI-driven predictive maintenance and vehicle diagnostics",
      "Fleet monitoring and performance optimization using digital twins",
      "Real-time vehicle data analysis and insights",
    ],
  },
  engineering: {
    services: [
      "Virtual Reality (VR)",
      "Augmented Reality (AR)",
      "Mixed Reality (MR)",
      "Visual Simulation (VS)",
      "Digital Twins (DT)",
      "Artificial Intelligence (AI)",
    ],
    products: [
      "VIDERE",
      "AUGMENTOR",
      "PRODOC",
      "REMO 3D",
      "LAYAR",
      "INTBOT",
      "COLLAB",
    ],
    applicationAreas: [
      "Design visualization and review",
      "Equipment maintenance and repair training",
      "Process simulation and optimization",
      "AR-guided field service and maintenance",
      "Collaborative virtual design reviews",
      "Technical documentation and instruction",
      "Product visualization and experience",
      "Assembly and disassembly training",
      "Factory layout and facility planning",
      "Ergonomics and human factor analysis",
      "Remote assistance and expert support for field engineers",
      "Interactive work instructions and digital manuals",
      "Safety training and hazard simulation",
      "Digital twin-based monitoring of equipment and systems",
      "Predictive maintenance and performance optimization",
      "Real-time data visualization and operational insights",
      "AI-powered chatbot support for technical queries and documentation access",
      "Simulation of complex systems and workflows for optimization",
    ],
  },
  mining: {
    services: [
      "Virtual Reality (VR)",
      "Augmented Reality (AR)",
      "Mixed Reality (MR)",
      "Visual Simulation (VS)",
      "Digital Twins (DT)",
      "Artificial Intelligence (AI)",
    ],
    products: [
      "Trian3DBuilder",
      "VRSAFE",
      "REMO 3D",
      "AUGMENTOR",
      "PRODOC",
      "INTBOT",
    ],
    applicationAreas: [
      "Heavy equipment operation and maintenance training",
      "Mining vehicles and Oil & Gas rig systems operation and maintenance",
      "Underground navigation and safety training",
      "Mine safety and emergency response training",
      "Industrial equipment usage simulation",
      "Mining operations and process simulation",
      "AR-guided field maintenance support",
      "Emergency evacuation and disaster simulation",
      "Remote assistance for field technicians",
      "Virtual mine planning and layout visualization",
      "Worker onboarding and skill development programs",
      "Real-time monitoring of mining equipment using digital twins",
      "Predictive maintenance and asset performance optimization",
      "AI-powered chatbot support for operational guidance and safety protocol",
    ],
  },
  transport: {
    services: [
      "Virtual Reality (VR)",
      "Augmented Reality (AR)",
      "Mixed Reality (MR)",
      "Visual Simulation (VS)",
      "Digital Twins (DT)",
      "Artificial Intelligence (AI)",
    ],
    products: [
      "Trian3DBuilder",
      "SilverLining",
      "PRODOC",
      "AUGMENTOR",
      "LAYAR",
      "INTBOT",
      "Triton",
    ],
    applicationAreas: [
      "Driver and operator simulation and assessment",
      "Rail, road, and water transport systems training",
      "Route planning and operational simulation",
      "Vehicle maintenance and technical training",
      "Transport infrastructure visualization",
      "Traffic management and control simulation",
      "Port and harbor operations training and simulation",
      "Rail signaling and control system training",
      "Emergency response and accident management training",
      "AR-guided maintenance and inspection of vehicles and infrastructure",
      "Remote assistance for field technicians and operators",
      "Passenger safety and evacuation training",
      "Autonomous vehicle and smart transport system simulation",
      "Digital twin monitoring of vehicles and transport infrastructure",
      "Predictive maintenance and asset lifecycle management",
      "Real-time tracking and performance analytics",
      "AI-powered chatbot support for passenger services and operations",
      "Intelligent scheduling and route optimization using AI",
      "Smart city and integrated transport system simulation",
    ],
  },
  healthcare: {
    services: [
      "Virtual Reality (VR)",
      "Augmented Reality (AR)",
      "Mixed Reality (MR)",
      "Visual Simulation (VS)",
      "Digital Twins (DT)",
      "Artificial Intelligence (AI)",
    ],
    products: ["VRSAFE", "PRODOC", "INTBOT", "AUGMENTOR", "LAYAR", "VIDERE"],
    applicationAreas: [
      "Medical equipment (such as MR-Scan, CT-Scan) training and simulation",
      "Pharmaceutical equipment operation and maintenance training",
      "Pharmaceutical manufacturing and process training",
      "Healthcare procedure visualization and training",
      "Patient care and emergency response simulation",
      "Surgical planning and visualization",
      "AR-guided equipment guidance and support",
      "Clinical training and skill development using immersive simulations",
      "Anatomy visualization and medical education",
      "Remote assistance for medical equipment maintenance and troubleshooting",
      "Digital twin-based monitoring of medical equipment and facilities",
      "Predictive maintenance and performance optimization of healthcare assets",
      "AI-powered chatbot support for patient engagement and assistance",
      "Data-driven insights for improving patient care and operational efficiency",
      "Emergency preparedness and disaster response simulation in healthcare environments",
    ],
  },
  manufacturing: {
    services: [
      "Virtual Reality (VR)",
      "Augmented Reality (AR)",
      "Mixed Reality (MR)",
      "Visual Simulation (VS)",
      "Digital Twins (DT)",
      "Artificial Intelligence (AI)",
    ],
    products: [
      "AUGMENTOR",
      "PRODOC",
      "LAYAR",
      "INTBOT",
      "VIDERE",
      "VRSAFE",
      "PAINTX",
      "REMO 3D",
    ],
    applicationAreas: [
      "Equipment maintenance and operator training",
      "Worker safety and compliance training",
      "Production process simulation",
      "AR-guided assembly and disassembly workflows",
      "Digital twin for manufacturing process monitoring",
      "Virtual prototyping and product design validation",
      "Factory layout planning and production line optimization",
      "Ergonomics and human factor analysis",
      "Remote assistance for maintenance and troubleshooting",
      "Interactive work instructions and digital manuals",
      "Robotics and automation simulation",
      "Material handling and logistics simulation within plants",
      "Predictive maintenance and asset performance optimization",
      "Real-time monitoring and analytics of production systems",
      "Knowledge management and intelligent access to technical documentation",
    ],
  },
  gaming: {
    services: [
      "Virtual Reality (VR)",
      "Augmented Reality (AR)",
      "Mixed Reality (MR)",
      "Visual Simulation (VS)",
      "Digital Twins (DT)",
      "Artificial Intelligence (AI)",
    ],
    products: [
      "TORQUE",
      "COLLAB",
      "REMO 3D",
      "SilverLining",
      "Triton",
      "INTBOT",
    ],
    applicationAreas: [
      "Immersive VR and AR game development",
      "Multiplayer simulation-based gaming experiences",
      "AI-driven non-player characters and adaptive gameplay",
      "Serious games for training and education",
      "Interactive 3D content and animation",
      "Entertainment and interactive experiences",
      "Mixed reality gaming with real-world interaction",
      "Physics-based simulation for realistic gameplay",
      "Gamification of training and learning experiences",
      "Virtual worlds and metaverse experience development",
    ],
  },
};

// Suppress unused import warning for Glasses
const _glasses = Glasses;
void _glasses;
